### ISSUE TITLE
Path mapping help needed (Plex on Ubuntu, Script on Windows, Media on Unraid)

### ISSUE THREAD

**Issue by dezerving** [stevezau/plex_generate_vid_previews#52]
Hello, I need some help with path mapping. Not sure why I can't figure this out but hoping some smart people in here can give me a hand.

I am running Plex on an Ubuntu 22.04 server, my media is located on an Unraid server and the script is running on a Windows server.

Plex database on Ubuntu is at `/var/lib/plexmediaserver...`. I've exported that SMB share and it is visible at `\\<server>\\plexdb\Media` on both my Windows machine and a separate Mac machine.

The issue seemingly is at the next point which is the path mapping for the actual media itself. 

Plex sees all the media under `/mnt/nfs` (which is an exported NFS share from Unraid) so for movies it would be `/mnt/nfs/movies` and so forth. That same Unraid share I have mounted to `D:\media` as an SMB share on Windows. It is visible. The only difference between the share on Windows and Ubuntu is the root path. I thought I had the correct .env based on my scenario but it doesn't appear so and I can't seem to figure it out.

My .env is as follows:
```env
PLEX_URL=https://192.168.86.3:32400/
PLEX_TOKEN=<token>  
PLEX_BIF_FRAME_INTERVAL=10
THUMBNAIL_QUALITY=4
PLEX_LOCAL_MEDIA_PATH="\\\<server>\plexdb\Media" # this works btw
TMP_FOLDER=C:\Users\<user>\tmp
PLEX_TIMEOUT=60
PLEX_LOCAL_VIDEOS_PATH_MAPPING=D:\media
PLEX_VIDEOS_PATH_MAPPING="/mnt/nfs"
GPU_THREADS=5
CPU_THREADS=5
```

When running the script here is sample output:
```py
python plex_generate_previews.py
2024/10/16 15:45:38 | ℹ️  - GPU Detection (with AMD Support) was recently added
to this script.
2024/10/16 15:45:38 | ℹ️  - Please log issues here
https://github.com/stevezau/plex_generate_vid_previews/issues
2024/10/16 15:45:38 | ℹ️  - Found NVIDIA GPU
2024/10/16 15:45:38 | ℹ️  - Getting the media files from library 'Movies'
2024/10/16 15:45:59 | ℹ️  - Got 4000 media files for library Movies
⠋ Working... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--    0/40002024/10/16 15:45:59 | ❌  - Skipping as file not found /mnt/nfs/movies/1BR
(2019) {tmdb-611605}/1BR (2019) {tmdb-611605} [Bluray-1080p][DTS 5.1]-iFT.mkv
⠋ Working... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--    0/40002024/10/16 15:45:59 | ❌  - Skipping as file not found /mnt/nfs/movies/2 Fast 2
Furious (2003) {tmdb-584}/2 Fast 2 Furious (2003) {tmdb-584}
[Bluray-1080p][DTS-HD MA 5.1].mkv
2024/10/16 15:45:59 | ❌  - Skipping as file not found /mnt/nfs/movies/2 Guns
(2013) {tmdb-136400}/2 Guns (2013) {tmdb-136400} [Bluray-1080p][AC3 5.1].mkv
```

Would appreciate any insight on how to resolve this. I have checked all documentation and searched previous issues but can't seem to get an answer to my specific scenario. Thank you in advanced!

**Comment by stevezau** [comment]
I think you found a bug @dezerving. i just pushed version [1.2.3](https://github.com/stevezau/plex_generate_vid_previews/releases/tag/1.2.3) which should fix it. 

can you test ?

**Comment by dezerving** [comment]
> I think you found a bug @dezerving. i just pushed version [1.2.3](https://github.com/stevezau/plex_generate_vid_previews/releases/tag/1.2.3) which should fix it.
> 
> can you test ?

Hey thanks for that quick work. Looks like that does correctly translate the beginning of the path, but doesn't handle the rest of the path with the slashes (converting / to \). That would probably require a bit more work I assume. 

Not sure if there's anything I can do on my end to make Windows paths appear as or accept forward slashes.

```py
PS C:\files\apps\plex_generate_vid_previews> python plex_generate_previews.py
2024/10/16 17:59:48 | ℹ️  - GPU Detection (with AMD Support) was recently added
to this script.
2024/10/16 17:59:48 | ℹ️  - Please log issues here
https://github.com/stevezau/plex_generate_vid_previews/issues
2024/10/16 17:59:48 | ℹ️  - Found NVIDIA GPU
2024/10/16 17:59:48 | ℹ️  - Getting the media files from library 'Movies'
2024/10/16 17:59:58 | ℹ️  - Got 4000 media files for library Movies
⠋ Working... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--    0/40002024/10/16 17:59:58 | ❌  - Skipping as file not found D:\media/movies/2 Fast 2
Furious (2003) {tmdb-584}/2 Fast 2 Furious (2003) {tmdb-584}
[Bluray-1080p][DTS-HD MA 5.1].mkv
2024/10/16 17:59:58 | ❌  - Skipping as file not found D:\media/movies/2 States
(2014) {tmdb-259720}/2 States (2014) {tmdb-259720} [Bluray-1080p][DTS 5.1].mkv
2024/10/16 17:59:58 | ❌  - Skipping as file not found D:\media/movies/8 Found
Dead (2023) {tmdb-1035705}/8 Found Dead (2023) {tmdb-1035705} [Bluray-1080p][AC3
5.1]-OFT.mkv
```

**Comment by dezerving** [comment]
Just doing a quick look, it looks like we could use the `pathlib` module so the paths are correctly handled depending on OS.

https://medium.com/@ageitgey/python-3-quick-tip-the-easy-way-to-deal-with-file-paths-on-windows-mac-and-linux-11a072b58d5f

**Comment by stevezau** [comment]
@dezerving you are right.. I don't handle windows too well. Let's fix that.. 

Just confirming.. you are running the script directly right? not in docker?

**Comment by stevezau** [comment]
Ill sort this out in the next day or two.

**Comment by dezerving** [comment]
> Ill sort this out in the next day or two. 

Sounds good, looking forward to that update. Will help test as needed.

**Comment by dezerving** [comment]
In the meantime I was able to get this script to run with my setup using Docker (since you can use forward and backward slashes freely). I'll leave the documentation below (or PR if you want):

---

# Guide for Docker script, Ubuntu Plex, and Unraid (or any NAS) media location

> Note: this does not require you to change any paths within Plex itself (as opposed to the Unraid guide within the docs currently). I'll explain all the path mapping and volumes below.

### Assumptions:
- Media file location is on a NAS (Unraid for me)
	- File path for media files for this guide: `/mnt/user/data/media`
		- You have exported this as an SMB share and NFS share (NFS for linux and SMB for Windows)
			- SMB available at `\\<server or IP>\\data\media` on Windows
			- NFS shares available at `/<server or IP>:/mnt/user/data/media/<folder>` mounted at `/mnt/nfs/<folder>` within Ubuntu
				- Example: `/<server or IP>:/mnt/user/data/media/movies` is mounted at `/mnt/nfs/movies`
- Plex server is on linux-based system (Ubuntu for me)
	- Your media files path (path that Plex sees) is: `/mnt/nfs` (if different change accordingly)
		- Example file path in Plex: `/mnt/nfs/movies/1BR (2019)/1BR (2019).mkv`
	- You have exported your Plex database folder as an SMB share (`/var/lib/plexmediaserver...`)
		- My snippet for the share in `smb.conf` file as reference:
			```conf
		   [plexdb]
		   path = "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server"
   		   browsable = yes
   		   writable = yes
   		   read only = no
			```
- Script is being run on Docker (on Windows)
	- Use the .env file below as reference
	- Set `PLEX_LOCAL_MEDIA_PATH` to the exported Plex database folder
		- I mapped `plexdb` to `T:` drive on Windows 
		- Making the final path to the folder with the localhost folder in it as: `T:\Media`
	- At the bottom of the .env file I added volumes section where I defined the share from Unraid as type cifs, pretty self-explanatory
		- Then mounted that as a volume inside the docker container to `/mnt/nfs`
	- I also altered the way the GPU is accessed (copied from Immich I think) but it worked as the original way was giving me errors on Windows

### .env file:
```yaml
---
services:
  previews:
    image: stevezzau/plex_generate_vid_previews:latest
    container_name: plex-thumbs
    environment:
      - PLEX_URL=https://<plex_server_ip>:32400 
      - PLEX_TOKEN=<token>
      - PLEX_BIF_FRAME_INTERVAL=10
      - THUMBNAIL_QUALITY=4
      - PLEX_LOCAL_MEDIA_PATH=/media				# be sure this is the correct volume mapped from below
      - TMP_FOLDER=/tmp/previews							# probably want to make this RAM disk in the future
      - PLEX_TIMEOUT=60
      - GPU_THREADS=5
      - CPU_THREADS=5
    volumes:
      - T:/Media:/media													# volume of your plex db folder (SMB mapped to network drive)
      - plexmedia:/mnt/nfs											# CIFS mount of your actual media mapped at bottom of file
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu

volumes:
  plexmedia:
    driver_opts:
      type: cifs
      device: "//<server or IP>/data/media"
      o: username=user,password=password
```

Will reformat later but this is the gist.
