### ISSUE TITLE
Stuck at does not exist, please edit PLEX_LOCAL_MEDIA_PATH environment variable

### ISSUE THREAD

**Issue by goku-son** [stevezau/plex_generate_vid_previews#69]
Try as I may, I am not able to get his working. 

I am running the host on Ubuntu and in the same location where my plex server lives. Here is my media location from the host side:

```
frank@kepler:~/plexworld$ ls "/home/frank/plexworld/plex/Library/Application Support/Plex Media Server/Media"
localhost
```

Here is my docker compose configuration:

```
 previews:
    image: stevezzau/plex_generate_vid_previews:latest
    container_name: genthumbnails
    hostname: genthumbnails
    networks:
      mylan:
        ipv4_address: 10.0.100.105
    user: 1000:1000
    environment:
      - PLEX_URL=https://10.0.100.92:32400
      - PLEX_TOKEN=XXXX -->Removed for security
      - PLEX_BIF_FRAME_INTERVAL=5
      - THUMBNAIL_QUALITY=4
      - PLEX_LOCAL_MEDIA_PATH="/home/frank/plexworld/plex/Library/Application Support/Plex Media Server/Media"
      - TMP_FOLDER=/tmp/previews
      - PLEX_TIMEOUT=60
      - HWACCEL=qsv
      - VAAPI_DEVICE=/dev/dri/renderD128
      - CPU_THREADS=5
      - DEBUG_MODE=true
    volumes:
      - "/home/frank/plexworld/plex/Library/Application Support/Plex Media Server/Media:/Media"
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
```

I have tried several variations for the MEDIA PATH but still I get this:

```
"/home/frank/plexworld/plex/Library/Application
Support/Plex Media Server/Media" does not exist, please edit
PLEX_LOCAL_MEDIA_PATH environment variable
```
Any assistance would be greatly appreciated!

**Comment by stevezau** [comment]
You are mounting  "/home/frank/plexworld/plex/Library/Application Support/Plex Media Server/Media" to the "/Media" folder in the docker container. 

So, in your config your set PLEX_LOCAL_MEDIA_PATH to "/home/frank/plexworld/plex/Library/Application Support/Plex Media Server/Media"

But it should point to /Media

**Comment by goku-son** [comment]
That worked thank you! It seems to be running, but the logs show Skipping as file not found for all my library files. Do I need to map the volume where my actual media exists?

**Comment by stevezau** [comment]
Yes you need to map the media volumes also

**Comment by goku-son** [comment]
Thank you I think I am very close now. I am use intel igpu (docker compose in the orginal message), but I am seeing this for all of my media: 
```
Device creation failed: -22.', "Failed
to set value '/dev/dri/renderD128' for option 'vaapi_device': Invalid argument",
'Error parsing global options: Invalid argument', '']
```

**Comment by goku-son** [comment]
For the benefit of others. 

I recently set up the container with Intel iGPU (VAAPI) hardware acceleration and ran into a permissions issue that’s common for Docker users. The solution was to use Docker Compose’s group_add to add the container user to the render group (the group that owns /dev/dri/renderD128 on most systems).

Please add the following note or example to the documentation for Intel/VAAPI hardware acceleration:

**Docker Compose Example for Intel VAAPI**
```
services:
  previews:
    image: stevezzau/plex_generate_vid_previews:latest
    user: 1000:1000
    group_add:
      - 109  # Replace 109 with the GID of the 'render' group on your host (check with 'getent group render')
    devices:
      - /dev/dri:/dev/dri
    ...
```

**Why:**
The /dev/dri/renderD128 device is typically owned by the render group.
If the container user is not in this group, VAAPI hardware acceleration will fail with errors like:
```
No VA display found for device /dev/dri/renderD128.
Device creation failed: -22.
Failed to set value '/dev/dri/renderD128' for option 'vaapi_device': Invalid argument
Error parsing global options: Invalid argument
```
How to find the correct GID:
`getent group render`

Use the GID (e.g., 109) in the group_add directive.

This small addition would save a lot of troubleshooting for Intel GPU users running the container with non-root users.
Thanks for your awesome work!
